#cloud-config
package_update: true
package_upgrade: true

# Cấu hình user
users:
  - name: azureuser
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_pwauth: false
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

# Cấu hình SSH
ssh_pwauth: false
disable_root: true

# Cài đặt các package cơ bản
packages:
  - docker.io
  - unzip

runcmd:
  # Cấu hình Docker
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ${admin_username}
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  # Khởi động lại Docker service
  - systemctl restart docker
  - apt-get clean
  - apt-get autoremove -y 