#cloud-config
package_update: true
package_upgrade: true

# Cấu hình user
users:
  - name: azureuser
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_pwauth: true
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}

# Cấu hình SSH
ssh_pwauth: true
disable_root: true

# Cài đặt các package cơ bản
packages:
  - docker.io
  - unzip

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ${admin_username}
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - apt-get clean
  - apt-get autoremove -y 